language: python
python:
  - "3.6"      # current detault Python on Travis CI
  - "3.7"
# command to install dependencies
install:
  - pip install -rU requirements.txt
  - pip install -rU requirements-dev.txt
# command to run tests
script:
  - python setup.py test
